import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/layout'


const Home: NextPage = () => {
  return (
    <Layout >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Hello World
      </div>
    </Layout>
  )
}

export default Home
